## Project 2 : Abby Bosch, Jeanne Exantus, and Somto Agulefo

In [ ]:
#IMPORTANT ***RUN THIS FIRST***
!pip install pandas plotly dash networkx
!pip install dash==3.2.0 plotly

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (5.24.1)
Requirement already satisfied: dash in /usr/local/lib/python3.12/dist-packages (3.2.0)
Requirement already satisfied: networkx in /usr/local/lib/python3.12/dist-packages (3.6.1)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly) (9.1.4)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from plotly) (26.0)
Requirement already satisfied: Flask<3.2,>=1.0.4 in /usr/local/lib/python3.12/dist-packages (from dash) (3.1.3)
Requirement already satisfied: Werkzeug<3.2 in /usr/local/lib/python3.12/dist-packages (from dash) (3.1.8)
Requirement already satisfied: importlib-metadata in /usr/local/lib/python3.12/dist-packages (from dash) (8.7.1)
Requirement already satisfied: typing-extensions>=4.1.1 in /usr/local/lib/python3.12/dist-packages (from dash) (4.15.0)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from dash) (2.32.4)
Requirement already satisfied: retrying in /usr/local/lib/python3.12/dist-packages (from dash) (1.4.2)
Requirement already satisfied: nest-asyncio in /usr/local/lib/python3.12/dist-packages (from dash) (1.6.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from dash) (75.2.0)
Requirement already satisfied: blinker>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from Flask<3.2,>=1.0.4->dash) (1.9.0)
Requirement already satisfied: click>=8.1.3 in /usr/local/lib/python3.12/dist-packages (from Flask<3.2,>=1.0.4->dash) (8.3.2)
Requirement already satisfied: itsdangerous>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from Flask<3.2,>=1.0.4->dash) (2.2.0)
Requirement already satisfied: jinja2>=3.1.2 in /usr/local/lib/python3.12/dist-packages (from Flask<3.2,>=1.0.4->dash) (3.1.6)
Requirement already satisfied: markupsafe>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from Flask<3.2,>=1.0.4->dash) (3.0.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.12/dist-packages (from importlib-metadata->dash) (3.23.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->dash) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->dash) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->dash) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->dash) (2026.2.25)
Requirement already satisfied: dash==3.2.0 in /usr/local/lib/python3.12/dist-packages (3.2.0)
Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (5.24.1)
Requirement already satisfied: Flask<3.2,>=1.0.4 in /usr/local/lib/python3.12/dist-packages (from dash==3.2.0) (3.1.3)
Requirement already satisfied: Werkzeug<3.2 in /usr/local/lib/python3.12/dist-packages (from dash==3.2.0) (3.1.8)
Requirement already satisfied: importlib-metadata in /usr/local/lib/python3.12/dist-packages (from dash==3.2.0) (8.7.1)
Requirement already satisfied: typing-extensions>=4.1.1 in /usr/local/lib/python3.12/dist-packages (from dash==3.2.0) (4.15.0)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from dash==3.2.0) (2.32.4)
Requirement already satisfied: retrying in /usr/local/lib/python3.12/dist-packages (from dash==3.2.0) (1.4.2)
Requirement already satisfied: nest-asyncio in /usr/local/lib/python3.12/dist-packages (from dash==3.2.0) (1.6.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from dash==3.2.0) (75.2.0)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly) (9.1.4)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from plotly) (26.0)
Requirement already satisfied: blinker>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from Flask<3.2,>=1.0.4->dash==3.2.0) (1.9.0)
Requirement already satisfied: click>=8.1.3 in /usr/local/lib/python3.12/dist-packages (from Flask<3.2,>=1.0.4->dash==3.2.0) (8.3.2)
Requirement already satisfied: itsdangerous>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from Flask<3.2,>=1.0.4->dash==3.2.0) (2.2.0)
Requirement already satisfied: jinja2>=3.1.2 in /usr/local/lib/python3.12/dist-packages (from Flask<3.2,>=1.0.4->dash==3.2.0) (3.1.6)
Requirement already satisfied: markupsafe>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from Flask<3.2,>=1.0.4->dash==3.2.0) (3.0.3)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.12/dist-packages (from importlib-metadata->dash==3.2.0) (3.23.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->dash==3.2.0) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->dash==3.2.0) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->dash==3.2.0) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->dash==3.2.0) (2026.2.25)

In [ ]:
# NECESSARY LIBARIES + FRAMEWORKS

import plotly.express as px
import plotly.graph_objects as go
import plotly.io as pio

import dash
from dash import dcc, html, Input, Output, Dash
import pandas as pd
import plotly.express as px

# Load dataset
df = pd.read_csv("Provisional_COVID-19_Deaths_by_Place_of_Death_and_State_20260417.csv")
df.columns = df.columns.str.strip()

In [ ]:
df.head()

,Data As Of,Start Date,End Date,Group,Year,Month,State,Place of Death,COVID-19 Deaths,Total Deaths,Pneumonia Deaths,Pneumonia and COVID-19 Deaths,Influenza Deaths,"Pneumonia, Influenza, or COVID-19 Deaths",Footnote
0,06/28/2023,01/01/2020,06/24/2023,By Total,NaN,NaN,United States,Total - All Places of Death,"1,136,076","11,569,541","1,123,100","565,185","21,901","1,713,431",NaN
1,06/28/2023,01/01/2020,06/24/2023,By Total,NaN,NaN,United States,"Healthcare setting, inpatient","743,207","3,592,622","841,478","459,861","13,943","1,137,676",NaN
2,06/28/2023,01/01/2020,06/24/2023,By Total,NaN,NaN,United States,"Healthcare setting, outpatient or emergency room","40,908","689,320","33,671","12,845","1,163","62,819",NaN
3,06/28/2023,01/01/2020,06/24/2023,By Total,NaN,NaN,United States,"Healthcare setting, dead on arrival","1,117","30,706",710,269,30,"1,588",NaN
4,06/28/2023,01/01/2020,06/24/2023,By Total,NaN,NaN,United States,Decedent's home,"114,319","3,903,005","85,184","29,560","3,415","172,344",NaN

In [ ]:
## Abby ##
import folium
import numpy as np
import plotly.express as px

In [ ]:
df2 = pd.read_csv("Provisional_COVID-19_Deaths_by_Place_of_Death_and_State_20260417.csv")
df.columns = df.columns.str.strip()

In [ ]:
df2.fillna(0, inplace=True)
df2

,Data As Of,Start Date,End Date,Group,Year,Month,State,Place of Death,COVID-19 Deaths,Total Deaths,Pneumonia Deaths,Pneumonia and COVID-19 Deaths,Influenza Deaths,"Pneumonia, Influenza, or COVID-19 Deaths",Footnote
0,06/28/2023,01/01/2020,06/24/2023,By Total,0.0,0.0,United States,Total - All Places of Death,"1,136,076","11,569,541","1,123,100","565,185","21,901","1,713,431",0
1,06/28/2023,01/01/2020,06/24/2023,By Total,0.0,0.0,United States,"Healthcare setting, inpatient","743,207","3,592,622","841,478","459,861","13,943","1,137,676",0
2,06/28/2023,01/01/2020,06/24/2023,By Total,0.0,0.0,United States,"Healthcare setting, outpatient or emergency room","40,908","689,320","33,671","12,845","1,163","62,819",0
3,06/28/2023,01/01/2020,06/24/2023,By Total,0.0,0.0,United States,"Healthcare setting, dead on arrival","1,117","30,706",710,269,30,"1,588",0
4,06/28/2023,01/01/2020,06/24/2023,By Total,0.0,0.0,United States,Decedent's home,"114,319","3,903,005","85,184","29,560","3,415","172,344",0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22837,06/28/2023,06/01/2023,06/24/2023,By Month,2023.0,6.0,Puerto Rico,Decedent's home,13,452,12,0,0,20,One or more data cells have counts between 1-9...
22838,06/28/2023,06/01/2023,06/24/2023,By Month,2023.0,6.0,Puerto Rico,Hospice facility,0,0,0,0,0,0,0
22839,06/28/2023,06/01/2023,06/24/2023,By Month,2023.0,6.0,Puerto Rico,Nursing home/long term care facility,0,118,0,0,0,0,0
22840,06/28/2023,06/01/2023,06/24/2023,By Month,2023.0,6.0,Puerto Rico,Other,0,40,0,0,0,0,0
22841,06/28/2023,06/01/2023,06/24/2023,By Month,2023.0,6.0,Puerto Rico,Place of death unknown,0,0,0,0,0,0,0

In [ ]:
#data cleaning to remove abnormalities
df2['COVID-19 Deaths'] = df2['COVID-19 Deaths'].astype(str).str.replace(',', '', regex=False)
df2['COVID-19 Deaths'] = pd.to_numeric(df2['COVID-19 Deaths'], errors='coerce')

#drop nas
df2.dropna(subset=['COVID-19 Deaths'], inplace=True)
#group the average deaths by state
avg_cov_deaths_by_state = df2.groupby('State')['COVID-19 Deaths'].mean().reset_index()

#drop rows that do not match state data/are redundant
rows_to_drop = ['District of Columbia', 'Puerto Rico', 'United States']
avg_cov_deaths_by_state = avg_cov_deaths_by_state[~avg_cov_deaths_by_state['State'].isin(rows_to_drop)]

In [ ]:
import folium
#Choropleth map creation

us_map = folium.Map(location = [39.8283, -98.5795], zoom_start = 4)

folium.Choropleth(
    geo_data = 'https://raw.githubusercontent.com/python-visualization/folium-example-data/main/us_states.json',
    name = 'choropleth',
    data = avg_cov_deaths_by_state,
    columns = ['State', 'COVID-19 Deaths'],
    key_on = 'feature.properties.name',
    fill_color = 'YlOrRd',
    legend_name= 'Average COVID-19 Deaths',
    fill_opacity = 0.7,
    line_opacity = 0.2
).add_to(us_map)

folium.LayerControl().add_to(us_map)
us_map

In [ ]:
#data cleaning to remove abnormalities
df2['Total Deaths'] = df2['Total Deaths'].astype(str).str.replace(',', '', regex=False)
df2['Total Deaths'] = pd.to_numeric(df2['Total Deaths'], errors='coerce')

#drop nas
df2.dropna(subset=['Total Deaths'], inplace=True)
#group the average total deaths by state
avg_tot_deaths_by_state = df2.groupby('State')['Total Deaths'].mean().reset_index()

#drop rows that do not match state data/are redundant
rows_to_drop = ['District of Columbia', 'Puerto Rico', 'United States']
avg_tot_deaths_by_state = avg_tot_deaths_by_state[~avg_tot_deaths_by_state['State'].isin(rows_to_drop)].reset_index(drop=True)

In [ ]:
#add state abbreviations so that plotly can identify each state
state_abbreviations = {
    'Alabama': 'AL', 'Alaska': 'AK', 'Arizona': 'AZ', 'Arkansas': 'AR', 'California': 'CA',
    'Colorado': 'CO', 'Connecticut': 'CT', 'Delaware': 'DE', 'Florida': 'FL', 'Georgia': 'GA',
    'Hawaii': 'HI', 'Idaho': 'ID', 'Illinois': 'IL', 'Indiana': 'IN', 'Iowa': 'IA',
    'Kansas': 'KS', 'Kentucky': 'KY', 'Louisiana': 'LA', 'Maine': 'ME', 'Maryland': 'MD',
    'Massachusetts': 'MA', 'Michigan': 'MI', 'Minnesota': 'MN', 'Mississippi': 'MS', 'Missouri': 'MO',
    'Montana': 'MT', 'Nebraska': 'NE', 'Nevada': 'NV', 'New Hampshire': 'NH', 'New Jersey': 'NJ',
    'New Mexico': 'NM', 'New York': 'NY', 'North Carolina': 'NC', 'North Dakota': 'ND', 'Ohio': 'OH',
    'Oklahoma': 'OK', 'Oregon': 'OR', 'Pennsylvania': 'PA', 'Rhode Island': 'RI', 'South Carolina': 'SC',
    'South Dakota': 'SD', 'Tennessee': 'TN', 'Texas': 'TX', 'Utah': 'UT', 'Vermont': 'VT',
    'Virginia': 'VA', 'Washington': 'WA', 'West Virginia': 'WV', 'Wisconsin': 'WI', 'Wyoming': 'WY'
}

avg_tot_deaths_by_state['State Abbrev'] = avg_tot_deaths_by_state['State'].map(state_abbreviations)

In [ ]:
#Bubble map

fig2 = px.scatter_geo(avg_tot_deaths_by_state, locations = 'State Abbrev', color = 'Total Deaths',
                     hover_name = 'State', size = 'Total Deaths',
                     projection = 'albers usa', title = 'Average Total Deaths',
                     locationmode='USA-states')
fig2.show()

In [ ]:
import pandas as pd

## Somto ##

df = pd.read_csv("Provisional_COVID-19_Deaths_by_Place_of_Death_and_State_20260417.csv")

df.columns = df.columns.str.strip()

df = pd.read_csv("Provisional_COVID-19_Deaths_by_Place_of_Death_and_State_20260417.csv")

df.columns = df.columns.str.strip()

df["COVID-19 Deaths"] = pd.to_numeric(df["COVID-19 Deaths"], errors="coerce")

df = df[df["Year"].between(2020, 2023)]

df = df.dropna(subset=["COVID-19 Deaths"])

region_map = {
    "New York":"Northeast","New Jersey":"Northeast","Pennsylvania":"Northeast",
    "Massachusetts":"Northeast","Connecticut":"Northeast","Rhode Island":"Northeast",
    "Vermont":"Northeast","New Hampshire":"Northeast","Maine":"Northeast",

    "Illinois":"Midwest","Ohio":"Midwest","Michigan":"Midwest","Indiana":"Midwest",
    "Wisconsin":"Midwest","Minnesota":"Midwest","Iowa":"Midwest","Missouri":"Midwest",
    "Kansas":"Midwest","Nebraska":"Midwest","South Dakota":"Midwest","North Dakota":"Midwest",

    "Texas":"South","Florida":"South","Georgia":"South","North Carolina":"South",
    "Virginia":"South","Tennessee":"South","Alabama":"South","South Carolina":"South",
    "Kentucky":"South","Louisiana":"South","Mississippi":"South","Arkansas":"South",
    "Oklahoma":"South","West Virginia":"South","Maryland":"South","Delaware":"South",
    "District of Columbia":"South",

    "California":"West","Washington":"West","Oregon":"West","Nevada":"West",
    "Arizona":"West","Utah":"West","Colorado":"West","New Mexico":"West",
    "Idaho":"West","Montana":"West","Wyoming":"West","Alaska":"West","Hawaii":"West"
}

df["Region"] = df["State"].map(region_map)

df = df.dropna(subset=["Region"])

# Aggregation Visualization 1 (Histogram)
fig_hist = px.histogram(
    df,
    x="COVID-19 Deaths",
    nbins=50,
    title="Distribution of COVID-19 Deaths (2020–2023)"
)

fig_hist.show()

# Aggregation Visualization 2 (Box Plot)
fig_box = px.box(
    df,
    x="Region",
    y="COVID-19 Deaths",
    color="Region",
    title="COVID-19 Deaths by Region"
)

fig_box.show()

In [ ]:
#Jeanne

#BUBBLE CHART (INTERACTIVE VISUALIZATION #1)

df = pd.read_csv("Provisional_COVID-19_Deaths_by_Place_of_Death_and_State_20260417.csv")
df.columns = df.columns.str.strip()

# Year column
df["Year"] = pd.to_numeric(df["Year"], errors="coerce")
df = df[df["Year"].between(2020, 2023)]

# From states to regions
region_map = {
    # Northeast
    "New York":"Northeast","New Jersey":"Northeast","Pennsylvania":"Northeast",
    "Massachusetts":"Northeast","Connecticut":"Northeast","Rhode Island":"Northeast",
    "Vermont":"Northeast","New Hampshire":"Northeast","Maine":"Northeast",

    # Midwest
    "Illinois":"Midwest","Ohio":"Midwest","Michigan":"Midwest","Indiana":"Midwest",
    "Wisconsin":"Midwest","Minnesota":"Midwest","Iowa":"Midwest","Missouri":"Midwest",
    "Kansas":"Midwest","Nebraska":"Midwest","South Dakota":"Midwest","North Dakota":"Midwest",

    # South
    "Texas":"South","Florida":"South","Georgia":"South","North Carolina":"South",
    "Virginia":"South","Tennessee":"South","Alabama":"South","South Carolina":"South",
    "Kentucky":"South","Louisiana":"South","Mississippi":"South","Arkansas":"South",
    "Oklahoma":"South","West Virginia":"South","Maryland":"South","Delaware":"South",
    "District of Columbia":"South",

    # West
    "California":"West","Washington":"West","Oregon":"West","Nevada":"West",
    "Arizona":"West","Utah":"West","Colorado":"West","New Mexico":"West",
    "Idaho":"West","Montana":"West","Wyoming":"West","Alaska":"West","Hawaii":"West"
}

df["region"] = df["State"].map(region_map)
df = df.dropna(subset=["region"])

# Keep only needed columns
df = df[[
    "region", "Year",
    "COVID-19 Deaths",
    "Pneumonia Deaths",
    "Influenza Deaths"
]]

# Convert to numeric values
for col in ["COVID-19 Deaths", "Pneumonia Deaths", "Influenza Deaths"]:
    df[col] = pd.to_numeric(df[col], errors="coerce")

df = df.dropna()

# Reshape (long format)
df_long = df.melt(
    id_vars=["region", "Year"],
    value_vars=["COVID-19 Deaths", "Pneumonia Deaths", "Influenza Deaths"],
    var_name="disease",
    value_name="deaths"
)

# Clean disease names
df_long["disease"] = df_long["disease"].str.replace(" Deaths", "", regex=False)
df_long = df_long.groupby(["region", "Year", "disease"])["deaths"].sum().reset_index() #aggregation

regions = ["Northeast", "Midwest", "South", "West"] #regions for slider

# Dash App
app = Dash(__name__)
app.layout = html.Div([
    html.H3(("US Disease Deaths Bubble Chart (2020–2023)"),
        style = {"color": "white"}
    ),

    dcc.Slider(
        id="region-slider",
        min=0,
        max=len(regions)-1,
        step=1,
        value=0,
        marks={
            i: {"label": regions[i], "style": {"color": "white", "font-weight": "bold"}}
           for i in range(len(regions))
        }
    ),

    dcc.Graph(id="bubble-chart")
])

# Callback
@app.callback(
    Output("bubble-chart", "figure"),
    Input("region-slider", "value")
)
def update_chart(region_index):

    selected_region = regions[region_index]
    filtered = df_long[df_long["region"] == selected_region]

    fig = px.scatter(
        filtered,
        x="deaths",
        y="Year",
        size="deaths",
        color="disease",
        size_max=70,
        title=f"{selected_region}: COVID-19, Pneumonia, Influenza Deaths",
        category_orders={"disease": ["COVID-19", "Pneumonia", "Influenza"]}
    )

    fig.update_layout(
        xaxis=dict(title="Number of Deaths", range=[0, 100000]),
        yaxis=dict(title="Year", range=[2019.5, 2023.5]),
        template="plotly_white"
    )

    return fig

if __name__ == "__main__":
    app.run(jupyter_mode="inline")

In [ ]:
  #BAR CHART (INTERACTIVE VISUALIZATION #2)

import dash
from dash import dcc, html, Input, Output, Dash
import pandas as pd
import plotly.express as px

df = pd.read_csv("Provisional_COVID-19_Deaths_by_Place_of_Death_and_State_20260417.csv")
df.columns = df.columns.str.strip()

df["COVID-19 Deaths"] = pd.to_numeric(df["COVID-19 Deaths"], errors="coerce")   # Convert numeric

df = df[df["Year"].between(2020, 2023)]   # Filter years 2020–2023
df = df[["State", "Year", "COVID-19 Deaths"]].dropna() # Relevant columns

# From states to regions
df["Region"] = df["State"].map(region_map)
df = df.dropna(subset=["Region"])

# Aggregate total covid deaths by state
df_agg = df.groupby(["Region", "State"])["COVID-19 Deaths"].sum().reset_index()

# Dash App
app = Dash(__name__)

app.layout = html.Div([
    html.H3(("COVID-19 Deaths by State (Region-Based)"),
       style = {"color": "white"}
    ),

    html.Label(("Select Region:"),
    style={"color": "white"}

    ),
    dcc.Dropdown(
        id="region-dropdown",
        options=[
            {"label": "Northeast", "value": "Northeast"},
            {"label": "Midwest", "value": "Midwest"},
            {"label": "South", "value": "South"},
            {"label": "West", "value": "West"}
        ],
        value="Northeast",
        clearable=False,
        style = {"backgroundColor": "#e6f1f9"}
    ),

    dcc.Graph(id="bar-chart")
])

# Callback
@app.callback(
    Output("bar-chart", "figure"),
    Input("region-dropdown", "value")
)
def update_bar(selected_region):

    dff = df_agg[df_agg["Region"] == selected_region]

    # Sort (descending order)
    dff = dff.sort_values(by="COVID-19 Deaths", ascending=True)

    fig = px.bar(
        dff,
        x="COVID-19 Deaths",
        y="State",
        orientation="h",
        title=f"COVID-19 Deaths by State — {selected_region}",
        text="COVID-19 Deaths"
    )

    fig.update_layout(
        xaxis=dict(title="Number of Deaths", range=[0, 100000]),
        yaxis=dict(title="States"),
        template="plotly_white",
        height=700
    )

    fig.update_traces(textposition="outside")

    return fig

if __name__ == "__main__":
    app.run(jupyter_mode="inline", port = 9006)